---
- name: get auth token
  uri:
    url: "https://{{ bigip_provider.server }}/mgmt/shared/authn/login"
    method: POST
    body_format: json
    return_content: true
    validate_certs: false
    body: {"username":"{{ bigip_provider.user }}","password":"{{ bigip_provider.password }}","loginProviderName":"tmos"}
    status_code: 200
  register: token
  retries: 3
  delay: 30
  delegate_to: localhost

- name: Download foo.conf
  get_url:
    url: 'https://raw.githubusercontent.com/rduchez/SMPP/master/AS3_declaration.json'
    dest: "~/as3.json"
    mode: '0440'


- name: POST AS3
  uri:
    url: "https://{{ bigip_provider.server }}/mgmt/shared/appsvcs/declare?async=true"
    method: POST
    headers:
      X-F5-Auth-Token: "{{ token.json.token.token }}"
    return_content: true
    validate_certs: false
    body_format: json
    body: "{{ lookup('file', '~/as3.json' ) }}"
    #body: "{{ atc.body.as3 }}"
    status_code: '202'
  register: as3Result
  until: as3Result.json.id
  delegate_to: localhost