---
- name: Execute AS3 declaration
  import_tasks: as3.yml



#
# following instructions found at 
# https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-service-provider-message-routing-administration-13-0-0/2.html
#

- name: Create message routing peer with additional settings
  bigip_message_routing_peer:
    name: mr-peer-smscs
    description: 'SMSC Static Peers'
    pool: /Common/pool-smsc-static-peers
    partition: Common
    transport_config: mr-transport-smpp
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
 
- name: Create a generic parser
  bigip_message_routing_protocol:
    name: mr-protocol-smpp-control
    description: 'SMPP Internal Messaging'
    no_response: yes
    disable_parser: yes
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
 
- name: Create a generic parser
  bigip_message_routing_protocol:
    name: mr-protocol-smpp
    description: 'Short Message Peer-to-Peer Protocol'
    no_response: yes
    disable_parser: yes
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
 
- name: Create a simple generic route
  bigip_message_routing_route:
    name: mr-route-smpp-default
    description: 'MR Route to all SMSCs'
    peers:
      - mr-peer-smscs
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
 
- name: Create a generic router profile
  bigip_message_routing_router:
    name: mr-router-smpp
    description: 'MR Router for SMPP Traffic'
    routes:
      - /Common/mr-route-smpp-default
    provider: "{{ bigip_provider }}"
  delegate_to: localhost

- name: Create generic transport config
  bigip_message_routing_transport_config:
    name: mr-transport-smpp
    description: 'Short Message Peer-to-Peer Static Peer Transport'
    profiles: "mr-protocol-smpp, f5-tcp-lan"
    rules:
      - /Common/__smpp_basic
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
